<a href="https://colab.research.google.com/github/sunnymanchanda/pytorch/blob/master/PyTorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
### Creating Tensors

In [0]:
import torch
import numpy as np

In [0]:
t1 = torch.tensor(4.)

In [4]:
t1.dtype

torch.float32

In [5]:
t2 = torch.tensor( [4., 5, 6] )
print(t2.dtype)
print(t2.shape)

torch.float32
torch.Size([3])


In [6]:
t3 = torch.tensor( [ [4., 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15] ] )
print(t3.dtype)
print(t3.shape)
print(t3)

torch.float32
torch.Size([4, 3])
tensor([[ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.]])


In [7]:
t4 = torch.tensor( [ [ [1., 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12] ], [ [1., 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12] ]  ] )
print(t4)
print(t4.dtype)
print(t4.shape)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]])
torch.float32
torch.Size([2, 4, 3])


In [0]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)


In [9]:
y = w*x + b
print(y)

tensor(17., grad_fn=<AddBackward0>)


In [10]:
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)
y.backward()
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)


dy/dx None
dy/dw None
dy/db None
dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


In [11]:
z = np.array([ [1., 2, 3], [4, 5,6] ])
print(z)
print(z.dtype)
print(z.shape)

[[1. 2. 3.]
 [4. 5. 6.]]
float64
(2, 3)


In [12]:
p = torch.from_numpy(z)
print(p)
print(p.dtype)
print(p.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.float64
torch.Size([2, 3])


In [13]:
r = p.numpy()
print(r, r.dtype, r.shape)

[[1. 2. 3.]
 [4. 5. 6.]] float64 (2, 3)


Part 2: Linear Regression with PyTorch

# Inputs temp, humidity, rainwall
# Output Yield of Apples and Oranges

In [0]:
input_lr = np.array( [ [73, 67, 43], [91, 88, 64], [87, 134, 58], [102, 43, 37], [69, 96, 70] ], dtype = 'float32')

In [29]:
output_lr = np.array( [ [56, 70], [81, 101], [119, 133], [22, 37], [103, 119] ], dtype = 'float32')
print(output_lr)

[[ 56.  70.]
 [ 81. 101.]
 [119. 133.]
 [ 22.  37.]
 [103. 119.]]


In [16]:
inp = torch.from_numpy(input_lr)
out = torch.from_numpy(output_lr)

print(inp)
print(type(inp), type(out))

tensor([[ 73.,  67.,  43.],
        [ 91.,  88.,  64.],
        [ 87., 134.,  58.],
        [102.,  43.,  37.],
        [ 69.,  96.,  70.]])
<class 'torch.Tensor'> <class 'torch.Tensor'>


In [0]:
w = torch.randn(2, 3, requires_grad = True)
b = torch.randn(2, requires_grad = True)


In [18]:
w.dtype
b.dtype
print(w)
print(b)

tensor([[ 1.3587,  1.9220, -0.4726],
        [ 0.0435, -1.2725, -0.7877]], requires_grad=True)
tensor([0.3953, 0.3128], requires_grad=True)


In [0]:
def model(x):
  return x @ w.t() + b

In [20]:
res = model(inp)
print(res)
print(out)

tensor([[ 208.0358, -115.6373],
        [ 262.9308, -158.1180],
        [ 348.7458, -212.0991],
        [ 204.1444,  -79.1092],
        [ 245.5804, -173.9818]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Loss Function: MSE

In [0]:
def mse(x1, x2):
  diff = (x1 - x2)**2
  return torch.sum( diff ) / diff.numel()


In [22]:
loss = mse(res, out)
print(loss)


tensor(48251.8945, grad_fn=<DivBackward0>)


In [0]:
# loss.backward()
# print(w)
# print(w.grad)

In [0]:
# with torch.no_grad():
#   alpha = (1e-5)
#   print(type(alpha))
#   print(w.dtype)
#   print(w.grad)
#   w = w - (alpha * w.grad)
#   b = b - (alpha * b.grad)
#   print(w.dtype)
#   print(w)
#   print(w.grad)
#   # w.grad.zero_()
#   # b.grad.zero_()


In [25]:
res = model(inp)
loss = mse(res, out)
print(loss)

tensor(48251.8945, grad_fn=<DivBackward0>)


In [0]:
for i in range (2000):
  res = model(inp)
  loss = mse(res, out)
  # print(loss)
  loss.backward()
  with torch.no_grad():
    w -= w.grad * 1e-5
    b -= b.grad * 1e-5
    w.grad.zero_()
    b.grad.zero_()


In [27]:
print(res)
print(out)

tensor([[ 57.4586,  70.4727],
        [ 80.2473,  99.7122],
        [122.6793, 134.8751],
        [ 22.1930,  37.5481],
        [ 97.9390, 117.2233]], grad_fn=<AddBackward0>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])


Linear Regression using PyTorch builtins 

In [0]:
import torch.nn as nn
from torch.utils.data import TensorDataset
from torch.utils.data import DataLoader

In [0]:
inputs = np.array([ [ 73.,  67.,  43.], [ 91.,  88.,  64.], [ 87., 134.,  58.], [102.,  43.,  37.], [ 69.,  96.,  70.], [ 73.,  67.,  43.], [ 91.,  88.,  64.], [ 87., 134.,  58.],
        [102.,  43.,  37.], [ 69.,  96.,  70.], [ 73.,  67.,  43.], [ 91.,  88.,  64.], [ 87., 134.,  58.], [102.,  43.,  37.], [ 69.,  96.,  70.] ], dtype = 'float32')
targets = np.array([
 [ 56.,  70.],
 [ 81., 101.],
 [119., 133.], 
 [ 22.,  37.],
 [103., 119.],
 [ 56.,  70.],
 [ 81., 101.],
 [119., 133.],
 [ 22.,  37.],
 [103., 119.],
 [ 56., 70.],
 [ 81., 101.],
 [119., 133.],
 [ 22.,  37.],
 [103., 119.] ], dtype = 'float32')

In [0]:
inputs = torch.from_numpy(inputs)
targets = torch.from_numpy(targets)
train_ds = TensorDataset(inputs, targets)
batch_size = 5
train_dl = DataLoader(train_ds, batch_size, shuffle = True)


In [0]:
# for xa, xb in train_dl:
#   print('batch')
#   print(xa)
#   print(xb)

In [49]:
#Define model
model = nn.Linear(3,2)
print(model)
print(model.weight)
print(model.bias)

Linear(in_features=3, out_features=2, bias=True)
Parameter containing:
tensor([[-0.3463,  0.1925, -0.1725],
        [ 0.2237, -0.1977, -0.1666]], requires_grad=True)
Parameter containing:
tensor([ 0.2790, -0.0786], requires_grad=True)


In [53]:
list( model.parameters() )

[Parameter containing:
 tensor([[-0.3463,  0.1925, -0.1725],
         [ 0.2237, -0.1977, -0.1666]], requires_grad=True),
 Parameter containing:
 tensor([ 0.2790, -0.0786], requires_grad=True)]

In [54]:
pred = model(inputs)
# print(pred)

tensor([[-19.5200,  -4.1653],
        [-25.3329,  -7.7911],
        [-14.0559, -16.7825],
        [-33.1497,   8.0666],
        [-17.2081, -15.2934],
        [-19.5200,  -4.1653],
        [-25.3329,  -7.7911],
        [-14.0559, -16.7825],
        [-33.1497,   8.0666],
        [-17.2081, -15.2934],
        [-19.5200,  -4.1653],
        [-25.3329,  -7.7911],
        [-14.0559, -16.7825],
        [-33.1497,   8.0666],
        [-17.2081, -15.2934]], grad_fn=<AddmmBackward>)


Loss function

In [0]:
import torch.nn.functional as F

In [0]:
loss_fn = F.mse_loss

In [63]:
loss = loss_fn(model(inputs), targets )
print(loss)

tensor(11084.8018, grad_fn=<MseLossBackward>)


In [0]:
opt = torch.optim.SGD(model.parameters() ,lr = 1e-5)

In [0]:
def fit(num_epochs, model,loss_fn, opt, train_dl):
  for i in  range(num_epochs):
    for xa, xb in train_dl:
      out = model(xa)
      loss = loss_fn(out, xb)
      loss.backward()
      opt.step()
      opt.zero_grad()
    if( (i+1) % 10 == 0):
      print('Epoch [{}/{}], Loss: {:.4f}'.format(i+1, num_epochs, loss) ) 
     



In [72]:
fit(100, model, loss_fn, opt, train_dl)

Epoch [10/100], Loss: 16.6223
Epoch [20/100], Loss: 12.0375
Epoch [30/100], Loss: 10.9390
Epoch [40/100], Loss: 8.7077
Epoch [50/100], Loss: 7.2244
Epoch [60/100], Loss: 5.9401
Epoch [70/100], Loss: 6.6068
Epoch [80/100], Loss: 6.2853
Epoch [90/100], Loss: 8.2662
Epoch [100/100], Loss: 7.8185


In [73]:
preds = model(inputs)
print(preds)
print(targets)

tensor([[ 57.3872,  70.5090],
        [ 80.5205,  98.4526],
        [121.9677, 137.2293],
        [ 22.0753,  38.3738],
        [ 98.4771, 114.5046],
        [ 57.3872,  70.5090],
        [ 80.5205,  98.4526],
        [121.9677, 137.2293],
        [ 22.0753,  38.3738],
        [ 98.4771, 114.5046],
        [ 57.3872,  70.5090],
        [ 80.5205,  98.4526],
        [121.9677, 137.2293],
        [ 22.0753,  38.3738],
        [ 98.4771, 114.5046]], grad_fn=<AddmmBackward>)
tensor([[ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.],
        [ 56.,  70.],
        [ 81., 101.],
        [119., 133.],
        [ 22.,  37.],
        [103., 119.]])
