<a href="https://colab.research.google.com/github/sunnymanchanda/pytorch/blob/master/PyTorch_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [0]:
### Creating Tensors

In [0]:
import torch

In [0]:
t1 = torch.tensor(4.)

In [5]:
t1.dtype

torch.float32

In [6]:
t2 = torch.tensor( [4., 5, 6] )
print(t2.dtype)
print(t2.shape)

torch.float32
torch.Size([3])


In [7]:
t3 = torch.tensor( [ [4., 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15] ] )
print(t3.dtype)
print(t3.shape)
print(t3)

torch.float32
torch.Size([4, 3])
tensor([[ 4.,  5.,  6.],
        [ 7.,  8.,  9.],
        [10., 11., 12.],
        [13., 14., 15.]])


In [8]:
t4 = torch.tensor( [ [ [1., 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12] ], [ [1., 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12] ]  ] )
print(t4)
print(t4.dtype)
print(t4.shape)

tensor([[[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]],

        [[ 1.,  2.,  3.],
         [ 4.,  5.,  6.],
         [ 7.,  8.,  9.],
         [10., 11., 12.]]])
torch.float32
torch.Size([2, 4, 3])


In [0]:
x = torch.tensor(3.)
w = torch.tensor(4., requires_grad = True)
b = torch.tensor(5., requires_grad = True)


In [10]:
y = w*x + b
print(y)

tensor(17., grad_fn=<AddBackward0>)


In [11]:
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)
y.backward()
print('dy/dx', x.grad)
print('dy/dw', w.grad)
print('dy/db', b.grad)


dy/dx None
dy/dw None
dy/db None
dy/dx None
dy/dw tensor(3.)
dy/db tensor(1.)


In [12]:
import numpy as np
z = np.array([ [1., 2, 3], [4, 5,6] ])
print(z)
print(z.dtype)
print(z.shape)

[[1. 2. 3.]
 [4. 5. 6.]]
float64
(2, 3)


In [13]:
p = torch.from_numpy(z)
print(p)
print(p.dtype)
print(p.shape)

tensor([[1., 2., 3.],
        [4., 5., 6.]], dtype=torch.float64)
torch.float64
torch.Size([2, 3])


In [14]:
r = p.numpy()
print(r, r.dtype, r.shape)

[[1. 2. 3.]
 [4. 5. 6.]] float64 (2, 3)


In [0]:
!pip install jovian --upgrade --quiet

[jovian] Error: Failed to detect Jupyter notebook or Python script. Skipping..
